### ISSUE TITLE
Omni Without Configs Doesn't Load

### ISSUE THREAD

**Issue by Moonsword22** [WEKarnesky/solarisskunkwerks#11]
**Describe the bug**
OmniMech base without configurations fails to load.

This is the error I get:
"Index: 0, Size: 0"

**To Reproduce**
1. Attempt to load the attached file.

**Expected behavior**
Loading an Omni without configurations should just bring up an unconfigured Omni ready to have a configuration added.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version Java 8u211

**Additional context**
This is a bug present in the last public release (0.68.3.1).

As a workaround, always make sure to put at least a Prime configuration on your Omnis.

[Battle Cobra BTL-C-2O.txt](https://github.com/WEKarnesky/solarisskunkwerks/files/3377386/Battle.Cobra.BTL-C-2O.txt)

**Comment by Moonsword22** [comment]
SSW tries to load the first configuration by default.  It just occurred to me that behavior might not have a sanity check to see if there _are_ configurations, which would mean it's just going to index 0 in an array with no members.  Could be a good first place to debug.

**Comment by Algebro7** [comment]
That's pretty much it. The exception is thrown in `MechReader.java` due to an empty Loadouts array:

```
// make sure the 'Mech is set to the first loadout.
m.SetCurLoadout( ((ifMechLoadout) m.GetLoadouts().get( 0 )).GetName() );
```

I'll try to figure out how to create an unconfigured omni as described and call that method if `m.GetLoadouts()` is a size 0 array.

**Comment by Moonsword22** [comment]
There's one attached to the bottom of this issue, just change the extension back to .ssw and it should work.

**Comment by Algebro7** [comment]
Can you try this build and see if everything works as expected after loading unconfigured omnis?

[SSW_0.7-Experimental.5.zip](https://github.com/WEKarnesky/solarisskunkwerks/files/3378136/SSW_0.7-Experimental.5.zip)

**Comment by Moonsword22** [comment]
Works well enough, although I think you should load to the Base Loadout/Base Chassis, not an unconfigured loadout.

![Annotation 2019-07-10 213926](https://user-images.githubusercontent.com/25834498/61015821-4f578d00-a35b-11e9-91b3-42dd25cba4c0.jpg)

Here's how to reproduce that program state:

1. Load the OmniMech from the original issue
2. Delete the auto-created variant

**Comment by Algebro7** [comment]
Awesome, that’s really helpful. I’ll let you know if I have any other questions.

**Comment by Algebro7** [comment]
Can you test this build?

[SSW_0.7-Experimental.5.zip](https://github.com/WEKarnesky/solarisskunkwerks/files/3380094/SSW_0.7-Experimental.5.zip)

**Comment by Moonsword22** [comment]
Looks good.  No save/load anomalies when I tell it to run the whole set, either.
