### ISSUE TITLE
Beginners Box Set Record Sheets printout

### ISSUE THREAD

**Issue by kevinn** [WEKarnesky/solarisskunkwerks#16]
The Beginners Box Sets throughout the years has simplified record sheets for beginning players. These record sheets are about half of an a4/letter paper size with Mech Data, Mech/Unit image, Hit Location table, Gunnery Skill, and an Armor Diagram. No heat, crit tables, and rear/internal structure diagrams. 

SSW can offer a simplified sheet print-out as outlined above (with BV rating for balancing purposes) for all of the available Mechs, Vees and the like. This could cater for pick-up games, accessibility, beginners, and/or those groups who wants something in-between Alpha Strike and standard Battletech games for simpler/faster play but grants access to all eras and units.

AFAIK, MML doesn't have this feature.

Example of the current quick-start record sheet:
![IMG_20190714_143807](https://user-images.githubusercontent.com/313263/61180210-c5067600-a645-11e9-8f6a-a093e014affe.jpg)

**Comment by WEKarnesky** [comment]
This actually needs to be posted to the Solaris-Skunk-Werks/solarisskunkwerks repo, as we are transitioning that way, Do you mind recreating it there?  If not, I'll do it later, but this way you can track as we plan for it.

**Comment by kevinn** [comment]
We have access to the main repo now? Nice.

I've re-posted on the main repo.

**Comment by WEKarnesky** [comment]
Yep, thanks,  I will close this one.
