### ISSUE TITLE
Question about equipment data file format

### ISSUE THREAD

**Issue by Warmag2** [WEKarnesky/solarisskunkwerks#17]
Trying to look at the equipment/weapon data. Can anyone give me an idea on what format the .dat files actually are?

**Comment by WEKarnesky** [comment]
Howdy!  To start with, we are actually over at https://github.com/Solaris-Skunk-Werks/solarisskunkwerks now,

That said the only way we currently have to add weapons is to use a tool that was most recently released with SSW 0.6.83.1 (the one available on their website) attached this this is a zip with the current ODS and the converter utility.  [This link is to a manual](https://drive.google.com/open?id=1mcgUH3UtdMU4JgHuvZQHFUfUbFTVlvnv
) explaining how to add and update equipment to this document.

[SSW EquipmentConvert.zip](https://github.com/WEKarnesky/solarisskunkwerks/files/3407289/SSW.EquipmentConvert.zip)
